base:
  angle_max_overtravel: 240
  angle_min_overtravel: 0
  angle_zero: 0
  angle_180: 180
  serial_pos_max: 1000
  serial_pos_min: 0
  servo_range_min: 0
  servo_range_max: 240
  zero_offset: 0
  servo_id: 6
  reverse: false
elbow:
  angle_max_overtravel: 240
  angle_min_overtravel: 0
  angle_zero: 0
  angle_180: 180
  servo_range_min: 0
  servo_range_max: 240
  serial_pos_max: 1000
  serial_pos_min: 0
  zero_offset: 0
  servo_id: 7
  reverse: false
gripper:
  angle_init: 25
  angle_max_enc: 316.23046875
  angle_max_motor: 175
  angle_min_enc: 231.767578125
  angle_min_motor: 5
  force_max: 50
  force_step_dist: 10
  force_threshold: 5
  force_time_step: 0.025
  offset_enc_to_motor: -217.654296875
  servo_id: -1
  reverse: false
shoulder:
  angle_max_overtravel: 180
  angle_min_overtravel: 0
  angle_zero: 0
  angle_180: 180
  serial_pos_max: 1000
  serial_pos_min: 0
  servo_range_min: 0
  servo_range_max: 240
  zero_offset: 0
  servo_id: 5
  reverse: false
